title: 전현규
description: 
site_title: '전현규 - 포트폴리오'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: JunkRoad
blog_url: 
email: guo32877@gmail.com
keybase_username: JunkRoad
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
